name: 'Deploy coverage report results'
description: 'A GitHub Action for deploying the reports and review results on GitHub.'
author: 'Parasoft'
branding:
  icon: 'aperture'
  color: 'blue'
inputs:
  workspace:
    description: 'Specify a path of the workspace directory.'
    required: true
  report:
    description: 'Specify the Parasoft coverage report path.'
    required: true
  javaInstallDirPath:
    description: 'Specify the JAVA installation folder path of the report.'
    required: true
runs:
  using: node20
  main: 'dist/index.js'