name: 'Deploy coverage report results'
description: 'A GitHub Action for deploying the reports and review results on GitHub.'
author: 'Parasoft'
branding:
  icon: 'aperture'
  color: 'blue'
inputs:
  repo_token:
    description: 'The GITHUB_TOKEN for this repo'
    required: true
    default: ${{ github.token }}
  path:
    description: 'report path'
    required: true
runs:
  using: node20
  main: 'dist/index.js'