name: Run SOAtest Action Demo

on:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    name: Test Action
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run local action
        uses: parasoft/run-soatest-action@1.0.0
        with:
          soatestWorkspace: 'soatest'

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports

  publish:
    name: Publish Reports
    needs: [build]
    permissions:
      checks: write
      pull-requests: write
      # only required for workflows in private repositories
      contents: read
      issues: read
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: reports

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upload results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: always()
        with:
          files: |
            reports\report-xunit.xml