# This is a basic workflow to help you get started with the Run Jtest action.
name: Run SOAtest Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    name: Test Action
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run local action
        uses: parasoft/run-soatest-action@jason_cicd805
        with:
          installDir: 'D:\Software\SOAtest & Virtualize\2023.1'
          soatestWorkspace: 'soatest'
          resource: 'TestAssets'
          settings: 'soatest/localsettings.properties'
          report: 'soatest/reports'
          reportFormat: 'xml,html'
          convertReportToXUnit: true
