# This is a basic workflow to help you get started with the Run Jtest action.
name: Run SOAtest Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    name: Test Action
    permissions:
        checks: write
        pull-requests: write
        # only required for workflows in private repositories
        contents: read
        issues: read
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run local action
        uses: parasoft/run-soatest-action@master
        with:
          soatestWorkspace: 'soatest'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Upload results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: always()
        with:
          files: |
            reports\report-xunit.xml
